# Configuring our pre-commit hooks to be used with pre-commit: https://pre-commit.com/

# ---------------------------------------------------------------------------------------------------------------------
# Terraform specific hooks
# ---------------------------------------------------------------------------------------------------------------------

# https://www.terraform.io/docs/commands/fmt.html
- id: terraform-fmt
  name: Terraform fmt
  description: The terraform fmt command is used to rewrite Terraform configuration files to a canonical format and style. This command applies a subset of the Terraform language style conventions, along with other minor adjustments for readability.
  entry: pre_commit_hooks/terraform/fmt.sh
  language: script
  files: \.tf$
  exclude: \.+.terraform\/.*$
  require_serial: true

# https://www.terraform.io/docs/commands/validate.html
- id: terraform-validate
  name: Terraform validate
  description: The terraform validate command validates all Terraform configuration files, referring only to the configuration and not accessing any remote services such as remote state, provider APIs, etc.
  entry: pre_commit_hooks/terraform/validate.sh
  language: script
  files: \.tf$
  exclude: \.+.terraform\/.*$
  require_serial: true

# https://github.com/terraform-linters/tflint
- id: tflint
  name: tflint
  description: TFLint is a Terraform linter focused on possible errors, best practices, etc. (Terraform >= 0.12)
  entry: pre_commit_hooks/terraform/tflint.sh
  language: script
  files: \.tf$
  exclude: \.+.terraform\/.*$

# ---------------------------------------------------------------------------------------------------------------------
# Golang specific hooks
# ---------------------------------------------------------------------------------------------------------------------

# https://golang.org/cmd/gofmt
- id: gofmt
  name: gofmt
  description: Gofmt is a tool that automatically formats Go source code.
  entry: pre_commit_hooks/go/gofmt.sh
  language: script
  files: \.go$
  exclude: vendor\/.*$

# https://godoc.org/golang.org/x/tools/cmd/goimports
- id: goimports
  name: goimports
  description: Command goimports updates your Go import lines, adding missing ones and removing unreferenced ones.
  entry: pre_commit_hooks/go/goimports.sh
  language: script
  files: \.go$
  exclude: vendor\/.*$

# https://github.com/golang/lint
- id: golint
  name: golint
  description: Golint is a linter for Go source code.
  entry: pre_commit_hooks/go/golint.sh
  language: script
  files: \.go$
  exclude: vendor\/.*$

# https://github.com/golangci/golangci-lint
- id: golangci-lint
  name: golangci-lint
  description: Linters Runner for Go.
  entry: pre_commit_hooks/go/golangci-lint.sh
  language: script
  files: \.go$
  exclude: vendor\/.*$
# ---------------------------------------------------------------------------------------------------------------------
# GNU Make specific hooks
# ---------------------------------------------------------------------------------------------------------------------
  - id: phony-targets
  name: phony-targets
  description: Linter for detecting targets marked as PHONY that doesn't exist.
  entry: pre_commit_hooks/make/phony-targets.sh
  language: script
  files: \Makefile$