// AsciiDoc TOC settings
:toc:
:toc-placement!:
:toc-title:

// GitHub Flavored Asciidoc (GFA). See https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74 for details.
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= pre-commit-hooks

This repository is a collection of https://pre-commit.com/[pre-commit hooks] used by https://mineiros.io[mineiros.io].

Currently, the following hooks are supported:

* terraform-fmt: The terraform fmt command is used to rewrite Terraform configuration `*.tf` files to a canonical format and style.
* terraform-validate: The terraform validate command validates all Terraform configuration `*.tf` files, referring only to the configuration and not accessing any remote services such as remote state, provider APIs, etc.
* tflint: TFLint is a Terraform linter focused on possible errors, best practices, etc. (Terraform >= 0.12). Applied to all Terraform configuration `*.tf` files.

== Installation
Install https://pre-commit.com/[pre-commit]. E.G. `brew install pre-commit`

== Usage

Create a `.pre-commit-config.yaml` inside your repositories. You can dynamically add and remove hooks inside the configuration file.
Please see the https://pre-commit.com/#usage[documentation] for further information.

```
repos:
  - repo: https://github.com/mineiros-io/pre-commit-hooks
    rev: <VERSION> # Check for the latest version: https://github.com/mineiros-io/pre-commit-hooks/releases
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
```

Once you created the configuration file inside your repository, you must run `pre-commit install` to activate the hooks.

That's it, pre-commit will now listen for changes in your files and run the checks accordingly.

=== Run Check against All Files

==== Example: Run A Specific Hook
```
pre-commit run terraform-validate --all-files
```

==== Example: Run All Hooks ( Useful Inside CI )
```

pre-commit run --all-files
```
